### ISSUE TITLE
add cloud/container resource detectors by default

### ISSUE THREAD

**Issue by trentm** [elastic/elastic-otel-node#128]
Add the available cloud/container resource detectors by default in ElasticNodeSDK:

```js
        const defaultConfig = {
            resourceDetectors: [
...
```

- One consideration might be to see about making them silent if they fail to detect resources. We don't want the noise if we have all these on by default.
- Do we want an `ELASTIC_OTEL_` config option to turn those off a la elastic-apm-node's `ELASTIC_APM_CLOUD_PROVIDER`? Something that would be easier than having to come up with a working subset for `OTEL_NODE_RESOURCE_DETECTORS`?
- If a user attempts to use `OTEL_NODE_RESOURCE_DETECTORS`, is there a value that will still get our Elastic detector that adds the distro resource keys?

**Comment by david-luna** [comment]
> We don't want the noise if we have all these on by default.

Maybe we can silent the `diag` warnings when resource detectors `detect` method is being called. Here showing the call stack
```
'    at Object.detect (/Users/david/Documents/repos/el/elastic-otel-node/packages/opentelemetry-node/lib/detectors.js:60:50)\\n'
  '    at /Users/david/Documents/repos/el/elastic-otel-node/node_modules/@opentelemetry/resources/build/src/detect-resources.js:56:41\\n'
  '    at Array.map (<anonymous>)\\n'
  '    at detectResourcesSync (/Users/david/Documents/repos/el/elastic-otel-node/node_modules/@opentelemetry/resources/build/src/detect-resources.js:54:85)\\n'
  '    at ElasticNodeSDK.start (/Users/david/Documents/repos/el/elastic-otel-node/node_modules/@opentelemetry/sdk-node/build/src/sdk.js:128:87)\\n'
  '    at ElasticNodeSDK.start (/Users/david/Documents/repos/el/elastic-otel-node/packages/opentelemetry-node/lib/elastic-node-sdk.js:129:15)\\n'
  '    at Object.<anonymous> (/Users/david/Documents/repos/el/elastic-otel-node/packages/opentelemetry-node/lib/start.js:43:5)\\n'
  '    at Module._compile (node:internal/modules/cjs/loader:1254:14)\\n'
  '    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\\n'
  '    at Module.load (node:internal/modules/cjs/loader:1117:32)'\n}","time":"2024-06-06T09:23:34.528Z"
```

Revealing the detection is done within the `start` method of the SDK. Silencing the logs in the start process is not a good idea IMHO since the user could miss important info

Running the express example with the default log level we only get one warning from `AwsEksDetector`
```bash
node -r @elastic/opentelemetry-node express-app.js

{"name":"elastic-otel-node","level":30,"preamble":true,"distroVersion":"0.1.3","env":{"os":"darwin 23.5.0","arch":"arm64","runtime":"Node.js v18.16.0"},"msg":"start Elastic OpenTelemetry Node.js Distribution","time":"2024-06-06T09:35:28.336Z"}
{"name":"elastic-otel-node","level":40,"msg":"No meter provider, using default","time":"2024-06-06T09:35:28.346Z"}
{"name":"elastic-otel-node","level":40,"msg":"Process is not running on K8S [Error: ENOENT: no such file or directory, access '/var/run/secrets/kubernetes.io/serviceaccount/token'] {\n  errno: -2,\n  code: 'ENOENT',\n  syscall: 'access',\n  path: '/var/run/secrets/kubernetes.io/serviceaccount/token'\n}","time":"2024-06-06T09:35:28.439Z"}
```

lowering the log level to `debug`, `verbose` or `all` will show more logs from the detectors but I guess this is expected from the user right?
