### ISSUE TITLE
Node.js default metrics dashboards

### ISSUE THREAD

**Issue by estolfo** [elastic/elastic-otel-node#132]
Let's make sure metrics dashboards are shown for the OTel distro in the Metrics tab and that the metrics shown are meaningful. This task might also require some UI task coordination and portable dashboard work.
If work was done for [this issue](https://github.com/elastic/apm/issues/806), it's possible some of it could be reused.

**Comment by david-luna** [comment]
As agreed in today's APM agents meeting (2024-05-14) the metrics tab should contain only runtime related metrics, in our case node metrics. There is already a PR to add these into semantic conventions https://github.com/open-telemetry/semantic-conventions/issues/990

We should wait for these metrics to land to start implementation (or check if there is already an instrumentation for that).

**Comment by david-luna** [comment]
Kibana PR created https://github.com/elastic/kibana/pull/199353

Next steps
- add `@opentelemetry/instrumentation-runtime-metrics` in EDOT for Node.js once published ([ref](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2507))
- release a new version of EDOT for Node.js

**Comment by david-luna** [comment]
Dashboard also backported to `8.x` (kudos to @trentm)
https://github.com/elastic/kibana/pull/200810
