### ISSUE TITLE
end-to-end sanity test with serverless

### ISSUE THREAD

**Issue by david-luna** [elastic/elastic-otel-node#170]
The goal is to check how an app instrumented by Elastic OTEL distro is shown in a serverless project. And detect if there is any issue related to the data being exported.

**Comment by david-luna** [comment]
Sanity test done twice:
- 1st on Monday April 29th with @estolfo 
- 2nd on Tuesday April 30th with @trentm 

The onboarding was straightforward and getting an API key was part of the process. We got a project up and receiving traces in few minutes. A couple of things were noticed/discussed
- the UI provides a copy button for each OTEL var which is okay. It would be nice to have a "copy all" button so you get all the configuration at once
- service map was not working (where should we raise the issue?)

**Comment by david-luna** [comment]
Issue created to fix the service map https://github.com/elastic/apm-index-service/issues/537

**Comment by trentm** [comment]
Shoudl we close this issue?

**Comment by david-luna** [comment]
> Shoudl we close this issue?

Now that we have the link to the related issue I also think we can close it :)
