### ISSUE TITLE
add missing HTTP/gRPC and HTTP/JSON exporters

### ISSUE THREAD

**Issue by trentm** [elastic/elastic-otel-node#212]
To use our distro in the OTel Demo requires (or would be helped by) shipping the gRPC exporters. 
Specifically, at least, the gRPC exporters for metrics and trace.

Currently we have these:

```
% npm ls -a | rg exporter | rg otlp | rg -v base
  ├─┬ @opentelemetry/exporter-logs-otlp-proto@0.51.1
  ├─┬ @opentelemetry/exporter-metrics-otlp-proto@0.51.1
  │ ├─┬ @opentelemetry/exporter-metrics-otlp-http@0.51.1
  │ ├─┬ @opentelemetry/exporter-trace-otlp-grpc@0.51.1
  │ ├─┬ @opentelemetry/exporter-trace-otlp-http@0.51.1
  │ ├─┬ @opentelemetry/exporter-trace-otlp-proto@0.51.1
```

These are from (a) whatever the upstream `sdk-node` package includes, plus (b) the otlp-proto exporters for metrics and logs, because our default is the `HTTP/proto` flavour.

Eventually `sdk-node` will probably include them all, but for now we should include the missing ones.

**Comment by david-luna** [comment]
There is a section in the spec regarding exporter protocols and their env vars. We should follow it so a user can switch `grpc` jus by setting the environment properly.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#specify-protocol
