### ISSUE TITLE
Node - Allow auto installation in k8s clusters

### ISSUE THREAD

**Issue by estolfo** [elastic/elastic-otel-node#255]

**Comment by trentm** [comment]
See https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/package.json

**Comment by trentm** [comment]
https://github.com/elastic/elastic-otel-node/pull/374 looks sufficient for this issue.
Users can use the `docker.elastic.co/observability/elastic-otel-node:edge` image for now, until we have the next versioned release of EDOT Node.js.

I have https://github.com/elastic/elastic-otel-node/pull/376 coming to improve the example a bit.

*Docs* are missing, but I'm not sure what the plan is there.
