### ISSUE TITLE
config review for GA

### ISSUE THREAD

**Issue by trentm** [elastic/elastic-otel-node#262]
Review all `ELASTIC_OTEL_` and `OTEL_` envvars/config that we should be supporting in the distro. Then create either separate issues, or use this as a tracking issue to support and test them.

**Comment by trentm** [comment]
- note possible `OTEL_ELASTIC_AUTO_SERVICE_NAME=true` from https://github.com/elastic/elastic-otel-java/issues/321

**Comment by david-luna** [comment]
The following table (in progress) contains all the env vars referred in [the spec](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/)


| **VAR** | **Handled in** | **Ref** |
| -------- | ----- | --- |
| OTEL_SDK_DISABLED | SDK  | [node-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/experimental/packages/opentelemetry-sdk-node/src/sdk.ts#L107) |
| OTEL_RESOURCE_ATTRIBUTES | SDK  | [env-detector](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-resources/src/detectors/EnvDetectorSync.ts#L60) |
| OTEL_SERVICE_NAME | SDK  | [env-detector](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-resources/src/detectors/EnvDetectorSync.ts#L72) |
| OTEL_LOG_LEVEL | SDK  | [node-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/experimental/packages/opentelemetry-sdk-node/src/sdk.ts#L115) |
| OTEL_PROPAGATORS | SDK  | [trace-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-sdk-trace-node/src/NodeTracerProvider.ts#L38) |
| OTEL_TRACES_SAMPLER | SDK  | [trace-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-sdk-trace-base/src/config.ts#L67) |
| OTEL_TRACES_SAMPLER_ARG | SDK  | [trace-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-sdk-trace-base/src/config.ts#L98) |
| OTEL_BSP_SCHEDULE_DELAY | SDK  | [trace-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts#L63) |
| OTEL_BSP_EXPORT_TIMEOUT | SDK  | [trace-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts#L67) |
| OTEL_BSP_MAX_QUEUE_SIZE | SDK  | [trace-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts#L59) |
| OTEL_BSP_MAX_EXPORT_BATCH_SIZE | SDK  | [trace-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts#L55) |
| OTEL_BLRP_SCHEDULE_DELAY | SDK  | [logs-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/experimental/packages/sdk-logs/src/export/BatchLogRecordProcessorBase.ts#L54) |
| OTEL_BLRP_EXPORT_TIMEOUT | SDK  | [logs-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/experimental/packages/sdk-logs/src/export/BatchLogRecordProcessorBase.ts#L57) |
| OTEL_BLRP_MAX_QUEUE_SIZE | SDK  | [logs-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/experimental/packages/sdk-logs/src/export/BatchLogRecordProcessorBase.ts#L53) |
| OTEL_BLRP_MAX_EXPORT_BATCH_SIZE | SDK  | [logs-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/experimental/packages/sdk-logs/src/export/BatchLogRecordProcessorBase.ts#L51) |
| OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT | SDK  | [logs-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/experimental/packages/sdk-logs/src/config.ts#L62) [trace-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-sdk-trace-base/src/utility.ts#L90) |
| OTEL_ATTRIBUTE_COUNT_LIMIT | SDK  | [logs-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/experimental/packages/sdk-logs/src/config.ts#L54) [trace-sdk](https://github.com/open-telemetry/opentelemetry-js/blob/b2778e1b2ff7b038cebf371f1eb9f808fd98107f/packages/opentelemetry-sdk-trace-base/src/utility.ts#L80) |

**Comment by david-luna** [comment]
This comment contains references to the nodejs specific env vars. References:
- https://opentelemetry.io/docs/zero-code/js/configuration/

### Enabled/disabled configurations
| **VAR** | Handled in | Refs |
| -------- | ----------- | ---- |
| OTEL_NODE_ENABLED_INSTRUMENTATIONS | Not handled | it is handled in [ato-instrumentations](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/0e96b2acdb553b17db7fcae0638443c38b04e968/metapackages/auto-instrumentations-node/src/utils.ts#L212) |
| OTEL_NODE_DISABLED_INSTRUMENTATIONS | Not handled | it is handled in [ato-instrumentations](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/0e96b2acdb553b17db7fcae0638443c38b04e968/metapackages/auto-instrumentations-node/src/utils.ts#L226) |

### Non-documented configurations
| **VAR** | Handled in | Refs |
| -------- | ----------- | ---- |
| OTEL_NODE_RESOURCE_DETECTORS |  | [sdk-node](https://github.com/open-telemetry/opentelemetry-js/blob/38f6689480d28dcbdafcb7b5ba4b14025328ffda/experimental/packages/opentelemetry-sdk-node/src/utils.ts#L44) available only: env,host,os,serviceInstance,process |

**Comment by david-luna** [comment]
Now for `ELASTIC_OTEL_*` vars we are going to enumerate them

| **VAR** | Description | Refs |
| -------- | ----------- | ---- |
| ELASTIC_OTEL_METRICS_DISABLED | To disable metrics instrumentation/export in the distro. Vanilla SDK has no metrics by default | [elastic-node-sdk](https://github.com/elastic/elastic-otel-node/blob/b195a18e99b5239972ddd4ab3b66a80de63da681/packages/opentelemetry-node/lib/elastic-node-sdk.js#L92) |
| ELASTIC_OTEL_LOG_DIRECTORY | (still in discussion) directory where to place the log file | [apm-issue](https://github.com/elastic/apm/issues/869) |
| ELASTIC_OTEL_LOG_TARGET | (still in discussion) target of the logs | [apm-issue](https://github.com/elastic/apm/issues/869) |

**Comment by david-luna** [comment]
Summary of the conclusions after meeting @trentm:
- exporters is under development and will get more support on envvars. The current ones supported by SDK & the distro are enough for the use cases we want to cover in GA.
- `zero-conf` envvars which are handled in the auto instrumentations package must be also handled in the distro for GA. The rationale behind is that the distro offers a replacement of this package allowing customers just to `--import` the distro and manage the included instrumentations via config
- `ELASTIC_OTEL_LOG_*` seem more specific in .NET land so is not a must for GA

Actions to be taken
- [ ] create new issue to support `OTEL_NODE_ENABLED_INSTRUMENTATIONS`, `OTEL_NODE_DISABLED_INSTRUMENTATIONS` & `OTEL_NODE_RESOURCE_DETECTORS `
- [ ] create new issue for writing a configuration document
- [ ] along with the config doc start writing the migration guide from elastic's "classic" agent to elastic's "otel distro"
