### ISSUE TITLE
[META 882] Check classic and OTel agents against serverless

### ISSUE THREAD

**Issue by obltmachine** [elastic/elastic-otel-node#305]
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/882
- Spec issue: https://github.com/elastic/apm/issues/883

**Comment by trentm** [comment]
I tested a simple example script instrumented with the OTel distro for Node.js
against a serverless deployment using 3 different flavours of encoding the
`OTEL_EXPORTER_OTLP_HEADERS` value (see specific values below):
- unencoded
- just encoding the space (via JS `encodeURI()`)
- encoding more chars, i.e. the equals-signs (via JS `encodeURIComponent()`, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

```
cd elastic-otel-node
npm ci
cd examples/

export OTEL_EXPORTER_OTLP_ENDPOINT="...REDACTED serverless endpoint URL..."

OTEL_SERVICE_NAME=example-a OTEL_EXPORTER_OTLP_HEADERS="Authorization=ApiKey a1Q0REDACTEDdLdjJGZw=="' \
    node -r @elastic/opentelemetry-node just-http-request.js
OTEL_SERVICE_NAME=example-b OTEL_EXPORTER_OTLP_HEADERS="Authorization=ApiKey%20a1Q0REDACTEDdLdjJGZw=="' \
    node -r @elastic/opentelemetry-node just-http-request.js
OTEL_SERVICE_NAME=example-c OTEL_EXPORTER_OTLP_HEADERS="Authorization=ApiKey%20a1Q0REDACTEDdLdjJGZw%3D%3D"' \
    node -r @elastic/opentelemetry-node just-http-request.js
```

They were all successful against an Elastic serverless deployment:

![Screenshot 2024-07-30 at 12 36 42 PM](https://github.com/user-attachments/assets/e600a4ad-b7c4-456c-a6d2-7dcb6a2e6c15)
